---
title: "Customer Tracker Dashboard"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
runtime: shiny
---

Inputs {.sidebar}
-------------------------------------

```{r}
library(shiny)

selectInput("seg", "Segment", c("Total", "Heavy", "Mainstream", "Focus1", "Focus2", "Specialty", "Diverse1", "Diverse2", "Other", "New"))
    
selectInput('grp', 'Group', c("Total", "Core", "Extra"))
    
radioButtons("per", "Period", c("Week", "YTD"))
```

```{r}
downloadHandler(

filename = function() {
 paste("Tracker", input$seg, input$grp, input$per, sep = "-") %>%
    paste0(., ".xlsx")
},
content = function(file) {
  pngfile <- paste0(file, ".png")
  wb <- createWorkbook()
  addWorksheet(wb, "Summary", gridLines = FALSE)
  ggsave(pngfile, p1(), "png", width = 6, height = 3)
  insertImage(wb, "Summary", file = pngfile)
  writeData(wb, "Summary", t0(), startRow = 16)
  addWorksheet(wb, sheetName = "Data")
  writeDataTable(wb, sheet = 2, dat())
  saveWorkbook(wb, file, overwrite = TRUE)
}
)
```


```{r setup}
library(flexdashboard)
library(readr)
library(tidyverse)
library(formattable)
library(openxlsx)
library(plotly)

curr <- read_csv("data/trackerCalcCurr.csv")
pre <- read_csv("data/trackerCalcPre.csv")
users <- read_csv("data/users.csv")

f <- function(x, y) {y / x - 1}
```


```{r format, include=FALSE}

  dat <- reactive({
    
    bind_cols(
      curr %>%
        filter(segment == input$seg) %>%
        select(ends_with(paste0(input$grp, input$per))) %>%
        rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
      pre %>%
        filter(segment == input$seg) %>%
        select(ends_with(paste0(input$grp, input$per))) %>%
        rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
    ) %>%
      mutate(
        Week = 1:52,
        RevenuePre = dollarsPre,
        RevenueCurr = dollarsCurr,
        Revenue = f(dollarsPre, dollarsCurr),
        CustomersPre = filter(users, segment == input$seg) %>% .$pre,
        CustomersCurr = filter(users, segment == input$seg) %>% .$curr,
        Customers = f(CustomersPre, CustomersCurr),
        VisitsPre = purchasesPre / CustomersPre,
        VisitsCurr = purchasesCurr / CustomersCurr,
        Visits = f(VisitsPre, VisitsCurr),
        ItemsPre = itemsPre / purchasesPre,
        ItemsCurr = itemsCurr / purchasesCurr,
        Items = f(ItemsPre, ItemsCurr),
        SpendPre = dollarsPre / itemsPre,
        SpendCurr = dollarsCurr / itemsCurr,
        Spend = f(SpendPre, SpendCurr)
      ) %>%
      filter(Week <= 22) %>%
      #arrange(desc(Week)) %>%
      select(
        Week, RevenuePre, RevenueCurr, Revenue,
        CustomersPre, CustomersCurr, Customers,
        VisitsPre, VisitsCurr, Visits,
        ItemsPre, ItemsCurr, Items,
        SpendPre, SpendCurr, Spend
      )
    
  })
  
```

Column
-------------------------------------

### Percentage Change by Week
    
```{r}
  pdat <- reactive({
    
    dat() %>%
      select(Week, Revenue, Customers, Visits, Items, Spend) %>%
      gather(seg, metric, -Week) %>%
      mutate(metric = round(100 * metric, 2)) %>%
      mutate(seg = factor(seg, levels = c("Spend", "Items", "Visits", "Customers", "Revenue")))
    
  })
  
  p1 <- reactive({

    ggplot(filter(pdat(), seg != "Revenue"), aes(Week, metric, fill = seg)) +
      geom_bar(stat = "Identity") + 
      geom_line(data = filter(pdat(), seg == "Revenue"), aes(Week, metric), col = "darkgrey") +
      scale_fill_manual(values = alpha(c("orange", "salmon", "darkgrey", "lightgreen", "lightblue"), 0.5)) +
      labs(x = "Week", y = "Percent", title = "Percentage change by Week") +
      theme_minimal() +
      theme(legend.title=element_blank())
    
  })
  
  renderPlotly({
    
    p1()
    
  })
```
    
### Data

```{r}

  t0 <- reactive({
    
    dat() %>%
      select(Week, RevenuePre, RevenueCurr, Revenue, Customers, Visits, Items, Spend)
    
  })


  renderTable({
    
    t0()

  })
  
```


