---
title: Customer Tracker Report
output: html_notebook
params:
  seg: 
    label: "Segment:"
    value: Total
    input: select
    choices: [Total, Heavy, Mainstream, Focus1, Focus2, 
              Specialty, Diverse1, Diverse2, Other, New]
  grp: 
    label: "Group:"
    value: Total
    input: select
    choices: [Total, Core, Extra]
  per: 
    label: "Period:"
    value: Week
    input: radio
    choices: [Week, YTD]
---

This report shows pecentage change by: `r params$seg` (segment); `r params$grp` (group); and `r params$per` (period).

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(plotly)
curr <- read_csv("trackerCalcCurr.csv")
pre <- read_csv("trackerCalcPre.csv")
users <- read_csv("users.csv")
```


```{r format, include=FALSE}
f <- function(x, y) {100 * (y / x - 1)}
dat <- bind_cols(
  curr %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
  pre %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
) %>%
  mutate(
    week = 1:52,
    dollarsPct = f(dollarsPre, dollarsCurr),
    usersPre = filter(users, segment == params$seg) %>% .$pre,
    usersCurr = filter(users, segment == params$seg) %>% .$curr,
    usersPct = f(usersPre, usersCurr),
    purUserPre = purchasesPre / usersPre,
    purUserCurr = purchasesCurr / usersCurr,
    purUserPct = f(purUserPre, purUserCurr),
    itemsPurPre = itemsPre / purchasesPre,
    itemsPurCurr = itemsCurr / purchasesCurr,
    itemsPurPct = f(itemsPurPre, itemsPurCurr),
    dollItemsPre = dollarsPre / itemsPre,
    dollItemsCurr = dollarsCurr / itemsCurr,
    dollItemsPct = f(dollItemsPre, dollItemsCurr)
  ) %>%
  filter(week <= 22) %>%
  select(
    week, dollarsPre, dollarsCurr, dollarsPct,
    usersPre, usersCurr, usersPct,
    purUserPre, purUserCurr, purUserPct,
    itemsPurPre, itemsPurCurr, itemsPurPct,
    dollItemsPre, dollItemsCurr, dollItemsPct
  )
```

```{r plot, echo=FALSE, fig.height=5, fig.width=10}
pdat <- dat %>%
  select(week, dollarsPct, usersPct, purUserPct, itemsPurPct, dollItemsPct) %>%
  gather(seg, metric, -week) %>%
  mutate(metric = round(metric, 2))

p1 <- ggplot(data = filter(pdat, seg != "dollarsPct"), aes(week, metric, fill = seg)) +
  geom_bar(stat = "Identity") + 
  geom_line(data = filter(pdat, seg == "dollarsPct"), aes(week, metric), col = "darkgrey") +
  scale_fill_manual(values = alpha(c("darkgrey", "lightgreen", "salmon", "lightblue", "orange"), 0.5)) +
  labs(x = "Week", y = "Percent", title = "Percentage change by Week") +
  theme_minimal()

ggplotly(p1)
```

```{r data, echo=FALSE}
dat %>%
  dat %>%
  select(week, dollarsPre, dollarsCurr, usersPre, usersCurr, purUserPre, 
         purUserCurr, itemsPurPre, itemsPurCurr,	dollItemsPre, dollItemsCurr) %>%
  mutate(purUserCurr = 100 * purUserCurr) %>%
  mutate(purUserPre = 100 * purUserPre) %>%
  mutate_at(vars(purUserPre:dollItemsCurr), round, 2) %>%
  knitr::kable()
```


