---
title: "Customer Tracker Dashboard"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
runtime: shiny
---

Inputs {.sidebar}
-------------------------------------

```{r}
library(shiny)

selectInput("seg", "Segment", c("Total", "Heavy", "Mainstream", "Focus1", "Focus2", "Specialty", "Diverse1", "Diverse2", "Other", "New"))
    
selectInput('grp', 'Group', c("Total", "Core", "Extra"))
    
radioButtons("per", "Period", c("Week", "YTD"))
```


```{r setup}
library(flexdashboard)
library(readr)
library(tidyverse)
library(shiny)
library(plotly)
curr <- read_csv("trackerCalcCurr.csv")
pre <- read_csv("trackerCalcPre.csv")
users <- read_csv("users.csv")
```


```{r format, include=FALSE}
f <- function(x, y) {100 * (y / x - 1)}
dat <- reactive({
  bind_cols(
  curr %>%
    filter(segment == input$seg) %>%
    select(ends_with(paste0(input$grp, input$per))) %>%
    rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
  pre %>%
    filter(segment == input$seg) %>%
    select(ends_with(paste0(input$grp, input$per))) %>%
    rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
) %>%
  mutate(
    week = 1:52,
    dollarsPct = f(dollarsPre, dollarsCurr),
    usersPre = filter(users, segment == input$seg) %>% .$pre,
    usersCurr = filter(users, segment == input$seg) %>% .$curr,
    usersPct = f(usersPre, usersCurr),
    purUserPre = purchasesPre / usersPre,
    purUserCurr = purchasesCurr / usersCurr,
    purUserPct = f(purUserPre, purUserCurr),
    itemsPurPre = itemsPre / purchasesPre,
    itemsPurCurr = itemsCurr / purchasesCurr,
    itemsPurPct = f(itemsPurPre, itemsPurCurr),
    dollItemsPre = dollarsPre / itemsPre,
    dollItemsCurr = dollarsCurr / itemsCurr,
    dollItemsPct = f(dollItemsPre, dollItemsCurr)
  ) %>%
  filter(week <= 22) %>%
  select(
    week, dollarsPre, dollarsCurr, dollarsPct,
    usersPre, usersCurr, usersPct,
    purUserPre, purUserCurr, purUserPct,
    itemsPurPre, itemsPurCurr, itemsPurPct,
    dollItemsPre, dollItemsCurr, dollItemsPct
  )
})
```

Column
-------------------------------------

### Percentage Change by Week
    
```{r}
pdat <- reactive({
  dat() %>%
  select(week, dollarsPct, usersPct, purUserPct, itemsPurPct, dollItemsPct) %>%
  gather(seg, metric, -week) %>%
  mutate(metric = round(metric, 2))
})

p1 <- reactive({
  ggplot(data = filter(pdat(), seg != "dollarsPct"), aes(week, metric, fill = seg)) +
  geom_bar(stat = "Identity") + 
  geom_line(data = filter(pdat(), seg == "dollarsPct"), aes(week, metric), col = "darkgrey") +
  scale_fill_manual(values = alpha(c("darkgrey", "lightgreen", "salmon", "lightblue", "orange"), 0.5)) +
  labs(x = "Week", y = "Percent") +
  theme_minimal()
})

renderPlotly({p1()})
```
    
### Data

```{r}
renderTable({
  dat() %>%
  select(week, dollarsPre, dollarsCurr, usersPre, usersCurr, purUserPre, 
         purUserCurr, itemsPurPre, itemsPurCurr,	dollItemsPre, dollItemsCurr) %>%
  mutate(purUserCurr = 100 * purUserCurr) %>%
  mutate(purUserPre = 100 * purUserPre) %>%
  mutate_at(vars(purUserPre:dollItemsCurr), round, 2)
})
```


