---
title: "Customer Tracker Report"
params:
  grp:
    choices:
    - Total
    - Core
    - Extra
    input: select
    label: 'Group:'
    value: Total
  per:
    choices:
    - Week
    - YTD
    input: radio
    label: 'Period:'
    value: Week
  seg:
    choices:
    - Total
    - Heavy
    - Mainstream
    - Focus1
    - Focus2
    - Specialty
    - Diverse1
    - Diverse2
    - Other
    - New
    input: select
    label: 'Segment:'
    value: Total
output:
  html_document: default
---

This report shows pecentage change by: `r params$seg` (segment); `r params$grp` (group); and `r params$per` (period).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(readr)
library(tidyverse)
library(plotly)
library(openxlsx)
library(formattable)
```

```{r pulldata, cache=TRUE}
curr <- read_csv("data/trackerCalcCurr.csv")
pre <- read_csv("data/trackerCalcPre.csv")
users <- read_csv("data/users.csv")
```

```{r format}
f <- function(x, y) {100 * (y / x - 1)}
dat <- bind_cols(
  curr %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
  pre %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
) %>%
  mutate(
    week = 1:52,
    dollarsPct = f(dollarsPre, dollarsCurr),
    usersPre = filter(users, segment == params$seg) %>% .$pre,
    usersCurr = filter(users, segment == params$seg) %>% .$curr,
    usersPct = f(usersPre, usersCurr),
    purUserPre = purchasesPre / usersPre,
    purUserCurr = purchasesCurr / usersCurr,
    purUserPct = f(purUserPre, purUserCurr),
    itemsPurPre = itemsPre / purchasesPre,
    itemsPurCurr = itemsCurr / purchasesCurr,
    itemsPurPct = f(itemsPurPre, itemsPurCurr),
    dollItemsPre = dollarsPre / itemsPre,
    dollItemsCurr = dollarsCurr / itemsCurr,
    dollItemsPct = f(dollItemsPre, dollItemsCurr)
  ) %>%
  filter(week <= 22) %>%
  select(
    week, dollarsPre, dollarsCurr, dollarsPct,
    usersPre, usersCurr, usersPct,
    purUserPre, purUserCurr, purUserPct,
    itemsPurPre, itemsPurCurr, itemsPurPct,
    dollItemsPre, dollItemsCurr, dollItemsPct
  )
```

```{r plot, fig.height=5, fig.width=10}
pdat <- dat %>%
  select(week, dollarsPct, usersPct, purUserPct, itemsPurPct, dollItemsPct) %>%
  gather(seg, metric, -week) %>%
  mutate(metric = round(metric, 2))

p1 <- ggplot(data = filter(pdat, seg != "dollarsPct"), aes(week, metric, fill = seg)) +
  geom_bar(stat = "Identity") + 
  geom_line(data = filter(pdat, seg == "dollarsPct"), aes(week, metric), col = "darkgrey") +
  scale_fill_manual(values = alpha(c("darkgrey", "lightgreen", "salmon", "lightblue", "orange"), 0.5)) +
  labs(x = "Week", y = "Percent", title = "Percentage change by Week") +
  theme_minimal()

ggplotly(p1)
```


```{r data}
out <- dat %>%
  select(week, dollarsPre, dollarsCurr, usersPre, usersCurr, purUserPre, 
         purUserCurr, itemsPurPre, itemsPurCurr,	dollItemsPre, dollItemsCurr) %>%
  mutate(purUserCurr = 100 * purUserCurr) %>%
  mutate(purUserPre = 100 * purUserPre) %>%
  mutate_at(vars(purUserPre:dollItemsCurr), round, 2)

tab <- dat %>%
  mutate(Week = week,
         Revenue = percent(dollarsPct / 100, digits = 1), 
         Customers = percent(usersPct / 100, digits = 1), 
         Visits = percent(purUserPct / 100, digits = 1),
         Items = percent(itemsPurPct / 100, digits = 1), 
         Spend = percent(dollItemsPct / 100, digits = 1)
         ) %>%
  select(Week, Revenue, Customers, Visits, Items, Spend)
```


```{r download, include=FALSE}
reportName <- paste0("Tracker-", params$seg, params$grp, params$per)
reportxls <- paste0(reportName, ".xlsx")
wb <- createWorkbook()
addWorksheet(wb, "Summary", gridLines = FALSE)
print(p1)
insertPlot(wb, "Summary", width = 8)
writeData(wb, "Summary", out, startRow = 21)
saveWorkbook(wb, reportxls, overwrite = TRUE)
```

```{r email}
library(rmarkdown)
library(blastula)
library(formattable)

email <- compose_email(
body = "
Hello Team,

Here is the report for {reportName}.

{add_ggplot(p1, width = 6, height = 3)}

{formattable(head(tab))}

- Nathan
  "
)

rmarkdown::output_metadata$set(
  rsc_email_subject = reportName,
  rsc_email_body_html = email$html_str,
  rsc_email_images = email$images,
  rsc_output_files = list(reportxls),
  rsc_email_attachments = list(reportName)
)
```

[`Download Report`](`r reportxls`)

