---
title: "Customer Tracker Report"
output: powerpoint_presentation
date: "`r Sys.Date()`"
params:
  seg: 
    label: "Segment:"
    value: Total
    input: select
    choices: [Total, Heavy, Mainstream, Focus1, Focus2, 
              Specialty, Diverse1, Diverse2, Other, New]
  grp: 
    label: "Group:"
    value: Total
    input: select
    choices: [Total, Core, Extra]
  per: 
    label: "Period:"
    value: Week
    input: radio
    choices: [Week, YTD]
---

## Overview

Data were compared from pre and post periods by week. This report shows pecentage change by:

* `r params$seg` (segment)
* `r params$grp` (group)
* `r params$per` (period)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(readr)
library(tidyverse)
library(plotly)
library(openxlsx)
```

```{r pulldata, cache=TRUE}
curr <- read_csv("data/trackerCalcCurr.csv")
pre <- read_csv("data/trackerCalcPre.csv")
users <- read_csv("data/users.csv")
```

```{r format}
f <- function(x, y) {100 * (y / x - 1)}
dat <- bind_cols(
  curr %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
  pre %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
) %>%
  mutate(
    week = 1:52,
    dollarsPct = f(dollarsPre, dollarsCurr),
    usersPre = filter(users, segment == params$seg) %>% .$pre,
    usersCurr = filter(users, segment == params$seg) %>% .$curr,
    usersPct = f(usersPre, usersCurr),
    purUserPre = purchasesPre / usersPre,
    purUserCurr = purchasesCurr / usersCurr,
    purUserPct = f(purUserPre, purUserCurr),
    itemsPurPre = itemsPre / purchasesPre,
    itemsPurCurr = itemsCurr / purchasesCurr,
    itemsPurPct = f(itemsPurPre, itemsPurCurr),
    dollItemsPre = dollarsPre / itemsPre,
    dollItemsCurr = dollarsCurr / itemsCurr,
    dollItemsPct = f(dollItemsPre, dollItemsCurr)
  ) %>%
  filter(week <= 22) %>%
  select(
    week, dollarsPre, dollarsCurr, dollarsPct,
    usersPre, usersCurr, usersPct,
    purUserPre, purUserCurr, purUserPct,
    itemsPurPre, itemsPurCurr, itemsPurPct,
    dollItemsPre, dollItemsCurr, dollItemsPct
  )
```

## Results

```{r plot, fig.height=7.5, fig.width=15}
pdat <- dat %>%
  select(week, dollarsPct, usersPct, purUserPct, itemsPurPct, dollItemsPct) %>%
  gather(seg, metric, -week) %>%
  mutate(metric = round(metric, 2))

p1 <- ggplot(data = filter(pdat, seg != "dollarsPct"), aes(week, metric, fill = seg)) +
  geom_bar(stat = "Identity") + 
  geom_line(data = filter(pdat, seg == "dollarsPct"), aes(week, metric), col = "darkgrey") +
  scale_fill_manual(values = alpha(c("darkgrey", "lightgreen", "salmon", "lightblue", "orange"), 0.5)) +
  labs(x = "Week", y = "Percent", title = "Percentage change by Week") +
  theme_minimal()

ggplotly(p1)
```

## Detail

```{r data}
out <- dat %>%
  select(week, dollarsPct, usersPct, purUserPct, itemsPurPct, dollItemsPct) %>%
  mutate_at(vars(dollarsPct:dollItemsPct), round, 2)

knitr::kable(head(out))
```

## Shiny App

```{r webshot, cache=TRUE, screenshot.opts=list(delay=3), fig.width=15, fig.cap="Click to open"}
if (is.null(webshot:::find_phantom())) webshot::install_phantomjs()
knitr::include_app('http://colorado.rstudio.com/rsc/content/1120/')
```

::: notes
Click on the image to open the Shiny app in RStudio Connect. Or visit online at http://colorado.rstudio.com/rsc/content/1120/.
:::

```{r download, include=FALSE}
reportName <- paste0("Tracker-", params$seg, params$grp, params$per, ".xlsx")
wb <- createWorkbook()
addWorksheet(wb, "Summary", gridLines = FALSE)
print(p1)
insertPlot(wb, "Summary", width = 8)
writeData(wb, "Summary", out, startRow = 21)
saveWorkbook(wb, reportName, overwrite = TRUE)
```

```{r email}
library(rmarkdown)
output_metadata$set("rsc_email_attachments" = list(reportName))
output_metadata$set("rsc_email_subject" = reportName)
```
