---
title: "Customer Tracker Report"
params:
  seg:
    choices:
    - Total
    - Heavy
    - Mainstream
    - Focus1
    - Focus2
    - Specialty
    - Diverse1
    - Diverse2
    - Other
    - New
    input: select
    label: 'Segment:'
    value: Total
  grp:
    choices:
    - Total
    - Core
    - Extra
    input: select
    label: 'Group:'
    value: Total
  per:
    choices:
    - Week
    - YTD
    input: radio
    label: 'Period:'
    value: Week
output:
  word_document: default
---

This report shows performance year over year by: `r params$seg` (segment); `r params$grp` (group); and `r params$per` (period).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(readr)
library(tidyverse)
```

```{r pulldata, cache=TRUE}
curr <- read_csv("data/trackerCalcCurr.csv")
pre <- read_csv("data/trackerCalcPre.csv")
users <- read_csv("data/users.csv")
```

```{r format}
f <- function(x, y) {(y / x - 1)}
dat <- bind_cols(
  curr %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesCurr", "itemsCurr", "dollarsCurr")),
  pre %>%
    filter(segment == params$seg) %>%
    select(ends_with(paste0(params$grp, params$per))) %>%
    rename_at(1:3, ~c("purchasesPre", "itemsPre", "dollarsPre"))
) %>%
  mutate(
    Week = 1:52,
    RevenuePre = dollarsPre,
    RevenueCurr = dollarsCurr,
    Revenue = f(dollarsPre, dollarsCurr),
    CustomersPre = filter(users, segment == params$seg) %>% .$pre,
    CustomersCurr = filter(users, segment == params$seg) %>% .$curr,
    Customers = f(CustomersPre, CustomersCurr),
    VisitsPre = purchasesPre / CustomersPre,
    VisitsCurr = purchasesCurr / CustomersCurr,
    Visits = f(VisitsPre, VisitsCurr),
    ItemsPre = itemsPre / purchasesPre,
    ItemsCurr = itemsCurr / purchasesCurr,
    Items = f(ItemsPre, ItemsCurr),
    SpendPre = dollarsPre / itemsPre,
    SpendCurr = dollarsCurr / itemsCurr,
    Spend = f(SpendPre, SpendCurr)
  ) %>%
  filter(Week <= 22) %>%
  #arrange(desc(Week)) %>%
  select(
    Week, RevenuePre, RevenueCurr, Revenue,
    CustomersPre, CustomersCurr, Customers,
    VisitsPre, VisitsCurr, Visits,
    ItemsPre, ItemsCurr, Items,
    SpendPre, SpendCurr, Spend
  )
```

```{r plot, fig.height=5, fig.width=10}
pdat <- dat %>%
  select(Week, Revenue, Customers, Visits, Items, Spend) %>%
  gather(seg, metric, -Week) %>%
  mutate(metric = round(100 * metric, 2)) %>%
  mutate(seg = factor(seg, levels = c("Spend", "Items", "Visits", "Customers", "Revenue")))

ggplot(filter(pdat, seg != "Revenue"), aes(Week, metric, fill = seg)) +
  geom_bar(stat = "Identity") + 
  geom_line(data = filter(pdat, seg == "Revenue"), aes(Week, metric), col = "darkgrey") +
  scale_fill_manual(values = alpha(c("orange", "salmon", "darkgrey", "lightgreen", "lightblue"), 0.5)) +
  labs(x = "Week", y = "Percent", title = "Percentage change by Week") +
  theme_minimal() +
  theme(legend.title=element_blank())
```


```{r data}
dat %>%
  select(Week, RevenuePre, RevenueCurr, Revenue, Customers, Visits, Items, Spend) %>%
  mutate_at(vars(Revenue:Spend), round, 2) %>%
  knitr::kable(.)
```
